name: project_name
description: "Project Name"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  dio: ^5.4.1
  shared_preferences: ^2.2.2

  design_system:
    path: ./packages/design_system
  melos: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true
