name: app_template
description: "Application Template"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.6.7
  go_router: 14.1.2
  dio: 5.4.1
  shared_preferences: 2.2.2
  melos: 6.0.0
  full_coverage: 1.0.0
  firebase_auth: 4.16.0
  connectivity_plus: 6.0.5
  in_app_purchase: 3.2.0
  flutter_secure_storage: 9.2.2
  firebase_remote_config: 4.3.8

  design_system:
    path: ./packages/design_system
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutterando_analysis: 0.0.2
  change_app_package_name: 1.2.0

flutter:
  uses-material-design: true
