name: app_template
description: "Application Template"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.6.7
  go_router: 14.1.2
  dio: 5.4.1
  shared_preferences: 2.3.1
  melos: 6.0.0
  full_coverage: 1.0.0

  design_system:
    path: ./packages/design_system
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutterando_analysis: 0.0.2

flutter:
  uses-material-design: true
