name: Continuous Delivery (CD)

on:
  push:
    tags:
      - "v*"

jobs:
  ci_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Run Continuous Integration
        uses: ./.github/workflows/ci.yaml

  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: ci_workflow

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get version from tag
        run: echo "GITHUB_STATE_VERSION=${GITHUB_REF#refs/tags/} >> GITHUB_ENV

      - name: Update version in pubspec.yaml
        run: |
          sed -i "s/version:.*\$/version: $GITHUB_STATE_VERSION/" pubspec.yaml

      - name: "Check Modified Dart Files"
        id: check_modified_files
        run: if git diff --exit-code 'pubspec.yaml'; then echo "modified=true" >> $GITHUB_STATE; else echo "modified=false" >> $GITHUB_STATE; fi

      - name: "Automatically Commit Changes"
        if: env.GITHUB_STATE == 'modified=true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: update version of pubspec.yaml automatically"
          git push

      - name: "Flutter Pub Get"
        run: flutter pub get

      - name: "Publish"
        run: "dart pub publish --dry-run"