name: Continuos Delivery (CD)

on:
  push:
    tags:
      - "v*"

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Melos
        run: dart pub global activate melos

      - name: "Bootstrap"
        run: melos bs

      - name: "Create JSON Environment File"
        run: |
          echo '{
            "API_KEY": "${{ secrets.API_KEY }}"",
            "BASE_URL": "${{ secrets.BASE_URL }}""
          }' > ./env/enviroment.json

      - name: "Build Android"
        run: flutter build appbundle --release --flavor prod --dart-define-from-file=./env/prod.enviroment.json

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/bundle/prodRelease/*.aab

  build_ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Melos
        run: dart pub global activate melos

      - name: "Bootstrap"
        run: melos bs

      - name: "Create JSON Environment File"
        run: |
          echo '{
            "API_KEY": "${{ secrets.API_KEY }}"",
            "BASE_URL": "${{ secrets.BASE_URL }}""
          }' > ./env/prod.enviroment.json

      - name: "Build iOS"
        run: flutter build ipa --release --flavor prod --dart-define-from-file=./env/prod.enviroment.json --no-codesign

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: build/ios/ipa/*.ipa