name: Continuos Integration (CI)

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/*.md"
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    name: Analyzer & Tests Reporter

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write
      checks: write
      actions: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: "Flutter Pub Get"
        run: flutter pub get

      - name: "Run Analyze"
        run: flutter analyze

      - name: "Run Format"
        run: dart format --set-exit-if-changed --line-length 120 .

      - name: "Run Dart Fixes"
        run: |
          dart fix --apply --code=unused_import
          dart fix --apply --code=always_specify_types
          dart fix --apply --code=always_declare_return_types

      - name: "Check Modified Dart Files"
        id: check_modified_files
        run: if git diff --exit-code '*.dart'; then echo "modified=true" >> $GITHUB_STATE; else echo "modified=false" >> $GITHUB_STATE; fi

      - name: "Automatically Commit Changes"
        if: env.GITHUB_STATE == 'modified=true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "fix: automatically fix code issues"
          git push

      - name: "Run Tests"
        run: flutter test --test-randomize-ordering-seed=random --coverage --machine > test-results.json

      - name: Check for existing and non-empty coverage file
        id: test_coverage_file
        run: if [ -s "coverage/lcov.info" ]; then echo "result=true" >> $GITHUB_OUTPUT ; else echo "result=false" >> $GITHUB_OUTPUT; fi

      - name: Verify Coverage
        if: steps.test_coverage_file.outputs.result == 'true'
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "coverage/lcov.info"
          min_coverage: 75
          exclude: "**/*_observer.dart **/change.dart"

      - name: "Test Reporter"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Results
          path: test-results.json
          reporter: flutter-json